# 服务器配置
server:
  port: ":9528" # 监听的端口

# 数据库配置
database:
  user: "class_order"
  password: "tanxue_class"
  host: "localhost"
  port: "3306"
  dbname: "class_order"
  charset: "utf8mb4"
  parseTime: "True"
  loc: "Local"

# JWT 配置
jwt:
  secret: "your-secret-key"
  expiration: 24  # hours 